### GET-Health
GET http://localhost:8080/actuator/health

### GET h2-console
GET http://localhost:8080/h2-console

### GET-Endpoint
GET http://localhost:8080/api/v1/pokemon/charizard

### POST-Endpoint
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "articleNumber": "100",
  "category": "Pokemon",
  "description": "Evolving Skies",
  "name": "Evolving Skies Booster Box",
  "price": 2000,
  "type": "Booster Box"
}